### ISSUE TITLE
Actualizar lista de integrantes

### ISSUE THREAD

**Issue by PietroMinaya** [PietroMinaya/VRP-COMPLE#1]

**Comment by Dana-Vallejos** [comment]
Dana Brigitte Vallejos Nesteres - U201910362

**Comment by PietroMinaya** [comment]
> Dana Brigitte Vallejos Nesteres - U201910362
Ok, nombre actualizado :D

**Comment by bdvela** [comment]
Bryan Deison Vela Alvarado - U20181A046

**Comment by PietroMinaya** [comment]
> Bryan Deison Vela Alvarado - U20181A046

Ok nombre actualizado :D

**Comment by AdrianChavezBerrocal** [comment]
Adrián Amir Chávez Berrocal-U201912855

**Comment by PietroMinaya** [comment]
> Adrián Amir Chávez Berrocal-U201912855

Ok, nombre actualizado 🌴

**Comment by raquel686** [comment]
Raquel Silvia Chávez Cruz-U201914478

**Comment by PietroMinaya** [comment]
> Raquel Silvia Chávez Cruz-U201914478

Ok, nombre actualizadoo :D
