### ISSUE TITLE
Generar Primera Version de Almacenes

### ISSUE THREAD

**Issue by PietroMinaya** [PietroMinaya/VRP-COMPLE#2]

**Comment by Dana-Vallejos** [comment]
Pietro, revisa si esto esta bien porfavor:

### Generacion del Data Set de Almacenes
- Para generar el data set de los almacenes vamos a usar una funcion en python la cual nos va a retornar una lista de listas, estas listas van a contener 2 elementos [x , y] los cuales me representan a las coordenadas x e y dentro del plano cartesiano respectivamente.

[almacenes.txt](https://github.com/PietroMinaya/VRP-COMPLE/files/7272889/almacenes.txt)

**Comment by PietroMinaya** [comment]
> Pietro, revisa si esto esta bien porfavor:
> 
> ### Generacion del Data Set de Almacenes
> * Para generar el data set de los almacenes vamos a usar una funcion en python la cual nos va a retornar una lista de listas, estas listas van a contener 2 elementos [x , y] los cuales me representan a las coordenadas x e y dentro del plano cartesiano respectivamente.
> 
> [almacenes.txt](https://github.com/PietroMinaya/VRP-COMPLE/files/7272889/almacenes.txt)


Si @Dana-Vallejos  lo veo bien, solo no te olvides de subir el codigo en formato .py al repo :D

**Comment by Dana-Vallejos** [comment]
> > Pietro, revisa si esto esta bien porfavor:
> > ### Generacion del Data Set de Almacenes
> > 
> > * Para generar el data set de los almacenes vamos a usar una funcion en python la cual nos va a retornar una lista de listas, estas listas van a contener 2 elementos [x , y] los cuales me representan a las coordenadas x e y dentro del plano cartesiano respectivamente.
> > 
> > [almacenes.txt](https://github.com/PietroMinaya/VRP-COMPLE/files/7272889/almacenes.txt)
> 
> Si @Dana-Vallejos lo veo bien, solo no te olvides de subir el codigo en formato .py al repo :D

OK esta bien
