### ISSUE TITLE
Definir espacio de búsqueda, estado inicial, posible estado final, transiciones.

### ISSUE THREAD

**Issue by PietroMinaya** [PietroMinaya/VRP-COMPLE#6]

**Comment by raquel686** [comment]
@PietroMinaya esta bien esto?
[issue.txt](https://github.com/PietroMinaya/VRP-COMPLE/files/7273981/issue.txt)

**Comment by PietroMinaya** [comment]
> @PietroMinaya esta bien esto? [issue.txt](https://github.com/PietroMinaya/VRP-COMPLE/files/7273981/issue.txt)

Si yo lo veo bien, ya puedes subirlo al readme :D
